grafana_reporter_node:
  ros__parameters:
    metrics_results_dir: /lidar_test_bench/results_locations/metrics_results
    lidar_frame: laser_link
    lidar: LSLIDAR
    lidar_cost: 999.0
    lidar_horizontal_fov_deg: 120.0
    lidar_vertical_fov_deg: 22.5
    bag_directory: /lidar_test_bench/results_locations/rosbags/CONFERENCE_ROOM_WHITE_WALL
    database_handler: Google
visualizer_node:
  ros__parameters:
    metrics_results_dir: /workspaces/polymath_workspace/metrics_results
    frame_id: map
    publish_rate_hz: 1.0
    lidar: LSLIDAR
    environment: white_wall_in_front_of_conference_room
