<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>lidar_eval_fixture</name>
  <version>0.0.0</version>
  <description>A package used for configuring the LIDAR evaluation Bench to compute metrics according to a certain lidar and a certain environment configuration</description>
  <maintainer email="aarush@polymathrobotics.com">Aarush Jain</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>replay_testing</exec_depend>
  <exec_depend>urdfdom_py</exec_depend>
  <exec_depend>lidar_transforms</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
