lidar_controller:
  ros__parameters:
    input_topic: /lidar_points
    bag_timeout: 5
    lidar_server_topic: /start_evaluation
    lidar: JT128
    test_results_dir: /workspaces/polymath_workspace/Pole_Tests
    metrics_results_dir: /workspaces/polymath_workspace/metrics_results
    environment: pole_test
    notion_database_id: 356c0b1ac5fa80fa8b29f29d3e2aa9a1
    notion_token: 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
    horizontal_resolution_deg: 0.4
    vertical_resolution_deg: 0.74
