lidar_bench_tf_broadcaster:
  ros__parameters:
    lidar_frame: hesai_lidar
lidar_baseline_node:
  ros__parameters:
    lidar_frame: hesai_lidar
    cloud_topic: /lidar_points
    z_padding:
      black_half_cylinder: 0.0
    y_padding:
      black_half_cylinder: 0.0
