lidar_bench_tf_broadcaster:
  ros__parameters:
    lidar_frame: laser_link
lidar_baseline_node:
  ros__parameters:
    lidar_frame: laser_link
    cloud_topic: /lslidar_point_cloud
    z_padding:
      white_wall: 0.1
    y_padding:
      white_wall: 0.101
