lidar_automation_manager:
  ros__parameters:
    angle_detection_enabled: false
    angles:
    - 141.0
    - 70.0
    - 0.0
    - -70.0
    - -141.0
    bag_recorder_directory: /lidar_test_bench/results_locations/rosbags/Outside_Office_Area
    bag_recording_duration: 10
    bench_initiate_service: ~/lidar_test_bench_initiate
    driver_command: ros2 run hesai_ros_driver hesai_ros_driver_node --ros-args -p
      config_path:=/lidar_test_bench/lidar_drivers/HesaiLidar_ROS_2.0/config/config.yaml
    driver_config_file: /lidar_test_bench/lidar_drivers/HesaiLidar_ROS_2.0/config/config.yaml
    lidar: JT128
    lidar_gui: prompt
    parameter_names: []
    pointcloud_topic: /lidar_points
    ros2_driver: hesai_ros_driver
    servo_angle_topic: /servo_angle
    start_evaluation_service: /start_evaluation
